services:
  # Backend service (Node.js)
  - type: web
    name: backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NASA_API_KEY
        value: sn1ktSgGaRPYYg80c69RFAceBTn6Apj0nqH1MS6w
      - key: PORT
        value: 5000
    autoDeploy: true # Automatically deploy new changes
    plan: free # Set to Render's free plan or upgrade as needed

  # Frontend service (React)
  - type: web
    name: frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
  
    plan: free
