export const spaceKeywords = [
    "Asteroid", "Astronomy", "Apollo", "Andromeda", "Alien",
    "Black Hole", "Big Bang", "Binary Star", "Buzz Aldrin", 
    "Comet", "Cosmos", "Constellation", "Crater", "Celestial Body",
    "Dark Matter", "Dwarf Planet", "Deep Space", "Discovery",
    "Earth", "Eclipse", "Exoplanet", "Extraterrestrial", 
    "Galaxy", "Gamma Ray", "Gravitational Waves", "Ganymede",
    "Hubble Telescope", "Heliosphere", "Hypernova", "Habitable Zone", 
    "International Space Station", "Io", "Interstellar", "Impact Crater", 
    "Jupiter", "Jet Propulsion", "Juno", 
    "Kepler", "Kuiper Belt", "Karman Line", 
    "Lunar Module", "Lagrange Point", "Light Year", "Lunar Eclipse", "Luna",
    "Mars", "Milky Way", "Meteor", "Meteor Shower", "Mission Control", 
    "Neptune", "Nebula", "NASA", "Nova", "Near-Earth Object", 
    "Orion", "Orbit", "Outer Space", "Observatory",
    "Planet", "Pluto", "Pulsar", "Photon", "Probe", "Protostar",
    "Quasar", "Quadrant", "Quantum Physics", 
    "Rocket", "Radiation", "Red Giant", "Rover", 
    "Solar System", "Star", "Satellite", "Supernova", "Space Shuttle", "Sputnik", 
    "Telescope", "Titan", "Trajectory", "Trappist-1", "Thermosphere", 
    "Universe", "Uranus", "Ultraviolet", 
    "Voyager", "Vesta", "Vacuum", "Venus",
    "Wormhole", "White Dwarf", "World Space Week", 
    "X-ray Astronomy", "Xenon", 
    "Yellow Dwarf", "Yuri Gagarin", 
    "Zodiac", "Zero Gravity", "Zenith"
];
